//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string otc { get; set; }
        public string login { get; set; }
        public Nullable<int> password { get; set; }
        public Nullable<int> sex_id { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Sex Sex { get; set; }
    }
}
